### PR TITLE
Add an option in the config file to setup manually the source name

### PR DESCRIPTION
**Pull request by mdebony**
This PR include #22 and #23, so they should be merged before merging this one.

### CODE REVIEW

**Comment by aleberti** [comment]
As I understand from the PR, the event/source name should be specified in the "general" section of the configuration file? Why one would put the event name as part of a configuration file? At least in LST, but I assume this is done also by others, a common configuration file is used for the same "class" or group of sources (e.g. one for BBH events, one for BNS, one for GBM etc). IMHO, it makes more sense to have the `event_name` specified through the call to `add_parsed_args` of `ObservationParameters` (e.g. same way one passes the skymap, pointings file etc.). Otherwise every time a new event come one needs to have an additional configuration file... @mseglar opinions?

**Comment by mseglar** [comment]
So in my opinion, one could advocate for any of both: option one, modifying each time the config file (one would either need to have another code to modify it automatically, or in offline cases, modifying by hand), option 2, treating the name as the rest of inputs as a parsed arg. I would rather go in the direction of a parsed arg, it is more straightforward. @mdebony

**Comment by mdebony** [comment]
Both could be implemented. The eventName on the config file is completely optional. I could add it to the parse args.

**Comment by mdebony** [comment]
@mseglar It is now possible to set the event name through parsed arguments.

**Comment by mdebony** [comment]
Yes

**Pull request merged**
